name: Analyze Links and Style

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1

  check-arm-templates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Test ARM Template
      id: armtest
      uses: aliencube/arm-ttk-actions@v0.3
      with:
        path: .

    - name: Test ARM Result
      shell: bash
      continue-on-error: true
      run: |
        echo "${{ toJSON(fromJSON(steps.armtest.outputs.results)) }}"