name: Analyze Links and Style

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1

  check-arm-templates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        path: install

    - name: Download ARM TTK
      uses: actions/checkout@v4
      with:
        repository: Azure/arm-ttk
        path: arm-ttk

    - name: Test ARM Template
      shell: pwsh
      run: |
        Import-Module ./arm-ttk/arm-ttk/arm-ttk.psd1
        Test-AzTemplate -TemplatePath ./install